# PyTorch

PyTorch是基于Python的科学计算包，其旨在服务两类场合：
* 替代NumPy发挥GPU潜能
* 提供了高度灵活性和效率的深度学习平台

PyTorch设计简洁，容易入门，本部分先介绍一些PyTorch的基础知识，让大家能够对PyTorch有一个大致的了解，并能够用PyTorch搭建一个简单的神经网络，然后在深入学习如何使用PyTorch实现各类网络结构。在学习过程，可能部分内容暂时不太理解，可先不予以深究，后续的课程将会对此进行深入讲解。



![PyTorch Demo](imgs/PyTorch.png)


## 1. Tensor基本用法

张量(Tensor)是一种专门的数据结构，非常类似于数组和矩阵。在PyTorch中，使用张量来编码模型的输入和输出，以及模型的参数。

张量类似于`NumPy`的`ndarray`，不同之处在于张量可以在GPU或其他硬件加速器上运行。事实上，张量和NumPy数组通常可以共享相同的底层内存，从而消除了复制数据的需要(请参阅使用NumPy的桥接)。张量还针对自动微分进行了优化，在Autograd部分中看到更多关于这一点的内介绍。

PyTorch基础的数据是张量(Tensor)，PyTorch 的很多操作好 NumPy 都是类似的，但是因为其能够在 GPU 上运行，所以有着比 NumPy 快很多倍的速度。本节内容主要包括 PyTorch 中的基本元素 Tensor 和 Variable 及其操作方式。

视频说明：
* [十分钟彻底搞懂张量](https://www.bilibili.com/video/BV1SB2gBFEyu)

### 1.1 Tensor定义与生成

In [1]:
import torch
import numpy as np

In [2]:
# 创建一个 numpy ndarray
numpy_tensor = np.random.randn(3, 4)

可以使用下面两种方式将numpy的ndarray转换到tensor上

In [4]:
pytorch_tensor1 = torch.tensor(numpy_tensor)
pytorch_tensor2 = torch.from_numpy(numpy_tensor)

print(numpy_tensor)
print(pytorch_tensor1)

[[ 0.10208897 -0.30496085  1.47042155 -1.02787063]
 [-0.93680187 -0.66481691  1.18452286  0.67190363]
 [ 0.24988125 -1.25331591  1.11211947 -0.66519237]]
tensor([[ 0.1021, -0.3050,  1.4704, -1.0279],
        [-0.9368, -0.6648,  1.1845,  0.6719],
        [ 0.2499, -1.2533,  1.1121, -0.6652]], dtype=torch.float64)


使用以上两种方法进行转换的时候，会直接将 NumPy ndarray 的数据类型转换为对应的 PyTorch Tensor 数据类型

同时也可以使用下面的方法将 `PyTorch Tensor` 转换为 `NumPy ndarray`

In [7]:
# 如果 pytorch tensor 在 cpu 上
numpy_array2 = pytorch_tensor1.numpy()

# 如果 pytorch tensor 在 gpu 上
numpy_array2 = pytorch_tensor1.cpu().numpy()

print(numpy_array2)

[[ 0.10208897 -0.30496085  1.47042155 -1.02787063]
 [-0.93680187 -0.66481691  1.18452286  0.67190363]
 [ 0.24988125 -1.25331591  1.11211947 -0.66519237]]


需要注意 GPU 上的 Tensor 不能直接转换为 NumPy ndarray，需要使用`.cpu()`先将 GPU 上的 Tensor 转到 CPU 上

### 1.2 PyTorch Tensor 使用 GPU 加速



使用GPU能够加快矩阵的计算，通过如下的方法能够检测当前的电脑上是否支持CUDA

In [8]:
import torch
torch.cuda.is_available()

True

我们可以使用以下两种方式将 Tensor 放到 GPU 上

In [10]:
# 第一种方式是定义 cuda 数据类型
dtype = torch.cuda.FloatTensor # 定义默认 GPU 的 数据类型
gpu_tensor = torch.randn(10, 20).type(dtype)

# 第二种方式更简单，推荐使用
gpu_tensor = torch.randn(10, 20).cuda(0) # 将 tensor 放到第一个 GPU 上
#gpu_tensor = torch.randn(10, 20).cuda(1) # 将 tensor 放到第二个 GPU 上

print(dtype)
print(gpu_tensor)

<class 'torch.cuda.FloatTensor'>
tensor([[ 0.1729,  0.4445,  0.7471, -0.1084,  0.3324, -0.8591,  1.4707,  2.0808,
          0.0243, -1.6763, -0.2791, -1.4333, -1.6580, -1.2843,  0.5809, -0.6248,
          0.2621, -0.3035,  0.1911,  1.1165],
        [ 0.2250, -0.2984,  0.2458, -2.3704, -0.3019, -0.5944,  0.1487, -1.8989,
         -0.0736, -0.5963,  0.2007, -1.4886, -1.6107,  0.5014,  0.8856, -0.6464,
         -0.8437, -0.4006,  0.2654,  0.0818],
        [-0.6854,  0.8539, -0.1271, -0.7754, -0.1883,  1.9728, -0.5320,  0.0493,
          2.0798, -0.5203,  0.6104, -1.3364,  1.5431,  0.8912,  0.5906,  1.9846,
          0.3169, -0.2364,  0.0226,  0.5022],
        [ 0.1130, -0.7565, -1.4786, -0.6632,  0.6879,  1.1706,  1.2788,  1.3019,
          0.0743, -1.3360, -0.1894, -0.7815,  1.8060,  1.6499, -1.2638,  0.5200,
         -0.0551, -2.1383,  0.0036,  0.4109],
        [ 0.8762, -0.8304, -0.0536,  1.1287,  1.6415,  0.8690,  1.9808,  1.4857,
         -1.0149, -1.0893,  0.4527, -1.4136, -1.7903, 

使用第一种方式将 tensor 放到 GPU 上的时候会将数据类型转换成定义的类型，而是用第二种方式能够直接将 tensor 放到 GPU 上，类型跟之前保持一致

推荐在定义 tensor 的时候就明确数据类型，然后直接使用第二种方法将 tensor 放到 GPU 上

而将 tensor 放回 CPU 的操作如下

In [11]:
cpu_tensor = gpu_tensor.cpu()

Tensor 属性的访问方式

In [12]:
# 可以通过下面两种方式得到 tensor 的大小
print(pytorch_tensor1.shape)
print(pytorch_tensor1.size())

torch.Size([3, 4])
torch.Size([3, 4])


In [13]:
# 得到 tensor 的数据类型
print(pytorch_tensor1.type())
print(gpu_tensor.type())

torch.DoubleTensor
torch.cuda.FloatTensor


In [14]:
# 得到 tensor 的维度
print(pytorch_tensor1.dim())

2


In [15]:
# 得到 tensor 的所有元素个数
print(pytorch_tensor1.numel())

12


## 2. Tensor的操作
Tensor 操作中的 API 和 NumPy 非常相似，如果熟悉 NumPy 中的操作，那么 tensor 基本操作是一致的，下面列举其中的一些操作

### 2.1 基本操作

In [16]:
x = torch.ones(3, 2)
print(x) # 这是一个float tensor

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [17]:
print(x.type())

torch.FloatTensor


In [18]:
# 将其转化为整形
x = x.long()
# x = x.type(torch.LongTensor)
print(x)

tensor([[1, 1],
        [1, 1],
        [1, 1]])


In [19]:
# 再将其转回 float
x = x.float()
# x = x.type(torch.FloatTensor)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [20]:
x = torch.randn(4, 3)
print(x)

tensor([[ 2.0401,  0.9547,  0.5138],
        [ 1.6914,  1.2873,  0.8358],
        [-0.2852,  2.6150, -1.8161],
        [ 0.5505,  0.2298,  0.1014]])


In [24]:
# 沿着行取最大值
max_value, max_idx = torch.max(x, dim=0)

In [25]:
# 每一行的最大值
max_value

tensor([2.0401, 2.6150, 0.8358])

In [26]:
# 每一行最大值的下标
max_idx

tensor([0, 2, 1])

In [27]:
# 沿着行对 x 求和
sum_x = torch.sum(x, dim=1)
print(sum_x)

tensor([3.5086, 3.8144, 0.5137, 0.8816])


In [28]:
# 增加维度或者减少维度
print(x.shape)
x = x.unsqueeze(0) # 在第一维增加
print(x.shape)
print(x)

torch.Size([4, 3])
torch.Size([1, 4, 3])
tensor([[[ 2.0401,  0.9547,  0.5138],
         [ 1.6914,  1.2873,  0.8358],
         [-0.2852,  2.6150, -1.8161],
         [ 0.5505,  0.2298,  0.1014]]])


In [29]:
x = x.unsqueeze(1) # 在第二维增加
print(x.shape)

torch.Size([1, 1, 4, 3])


In [30]:
x = x.squeeze(0) # 减少第一维
print(x.shape)
print(x)

torch.Size([1, 4, 3])
tensor([[[ 2.0401,  0.9547,  0.5138],
         [ 1.6914,  1.2873,  0.8358],
         [-0.2852,  2.6150, -1.8161],
         [ 0.5505,  0.2298,  0.1014]]])


In [31]:
x = x.squeeze() # 将 tensor 中所有的一维全部都去掉
print(x.shape)

torch.Size([4, 3])


In [32]:
x = torch.randn(3, 4, 5)
print(x.shape)

# 使用permute和transpose进行维度交换
x = x.permute(1, 0, 2) # permute 可以重新排列 tensor 的维度
print(x.shape)

x = x.transpose(0, 2)  # transpose 交换 tensor 中的两个维度
print(x.shape)

torch.Size([3, 4, 5])
torch.Size([4, 3, 5])
torch.Size([5, 3, 4])


In [37]:
# 使用 view 对 tensor 进行 reshape
x = torch.randn(3, 4, 5)
print(x.shape)

x = x.view(-1, 5) # -1 表示任意的大小，5 表示第二维变成 5
print(x.shape)

x = x.view(3, 20) # 重新 reshape 成 (3, 20) 的大小
print(x.shape)

torch.Size([3, 4, 5])
torch.Size([12, 5])
torch.Size([3, 20])


In [38]:
x = torch.randn(3, 4)
y = torch.randn(3, 4)

# 两个 tensor 求和
z = x + y
# z = torch.add(x, y)
print(z)

tensor([[ 1.5690,  0.0234,  1.6897,  1.4848],
        [ 0.7766,  0.4171,  0.9397,  0.0100],
        [-0.8918,  0.8735,  1.6475,  1.0586]])


### 2.2 `inplace`操作

PyTorch中大多数的操作都支持 `inplace` 操作，也就是可以直接对 tensor 进行操作而不需要另外开辟内存空间，方式非常简单，一般都是在操作的符号后面加`_`，比如

In [39]:
x = torch.ones(3, 3)
print(x.shape)

# unsqueeze 进行 inplace
x.unsqueeze_(0)
print(x.shape)

# transpose 进行 inplace
x.transpose_(1, 0)
print(x.shape)

torch.Size([3, 3])
torch.Size([1, 3, 3])
torch.Size([3, 1, 3])


In [40]:
x = torch.ones(3, 3)
y = torch.ones(3, 3)
print(x)

# add 进行 inplace
x.add_(y)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


## 练习题


* 查阅[PyTorch的Tensor文档](http://pytorch.org/docs/tensors.html)了解 tensor 的数据类型，创建一个 float64、大小是 3 x 2、随机初始化的 tensor，将其转化为 numpy 的 ndarray，输出其数据类型
* 查阅[PyTorch的Tensor文档](http://pytorch.org/docs/tensors.html)了解 tensor 更多的 API，创建一个 float32、4 x 4 的全为1的矩阵，将矩阵正中间 2 x 2 的矩阵，全部修改成2

## 参考
* [PyTorch官方说明文档](https://pytorch.org/docs/stable/)
* http://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html
* http://cs231n.github.io/python-numpy-tutorial/