# PyTorch

PyTorch是基于Python的科学计算包，其旨在服务两类场合：
* 替代NumPy发挥GPU潜能
* 提供了高度灵活性和效率的深度学习平台

PyTorch设计简洁，容易入门，本部分先介绍一些PyTorch的基础知识，让大家能够对PyTorch有一个大致的了解，并能够用PyTorch搭建一个简单的神经网络，然后在深入学习如何使用PyTorch实现各类网络结构。在学习过程，可能部分内容暂时不太理解，可先不予以深究，后续的课程将会对此进行深入讲解。



![PyTorch Demo](imgs/PyTorch.png)


## 1. Tensor基本用法

张量(Tensor)是一种专门的数据结构，非常类似于数组和矩阵。在PyTorch中，使用张量来编码模型的输入和输出，以及模型的参数。

张量类似于`NumPy`的`ndarray`，不同之处在于张量可以在GPU或其他硬件加速器上运行。事实上，张量和NumPy数组通常可以共享相同的底层内存，从而消除了复制数据的需要(请参阅使用NumPy的桥接)。张量还针对自动微分进行了优化，在Autograd部分中看到更多关于这一点的内介绍。

PyTorch基础的数据是张量(Tensor)，PyTorch 的很多操作好 NumPy 都是类似的，但是因为其能够在 GPU 上运行，所以有着比 NumPy 快很多倍的速度。本节内容主要包括 PyTorch 中的基本元素 Tensor 和 Variable 及其操作方式。

### 1.1 Tensor定义与生成

In [1]:
import torch
import numpy as np

In [2]:
# 创建一个 numpy ndarray
numpy_tensor = np.random.randn(3, 4)

可以使用下面两种方式将numpy的ndarray转换到tensor上

In [3]:
pytorch_tensor1 = torch.tensor(numpy_tensor)
pytorch_tensor2 = torch.from_numpy(numpy_tensor)

pytorch_tensor1

tensor([[-0.2132,  0.4186,  0.4007,  1.1361],
        [ 1.3502,  0.2401,  0.6191,  0.5228],
        [ 0.7740,  0.0468,  2.2317, -0.4603]], dtype=torch.float64)

使用以上两种方法进行转换的时候，会直接将 NumPy ndarray 的数据类型转换为对应的 PyTorch Tensor 数据类型

同时也可以使用下面的方法将 `PyTorch Tensor` 转换为 `NumPy ndarray`

In [4]:
# 如果 pytorch tensor 在 cpu 上
numpy_array = pytorch_tensor1.numpy()

# 如果 pytorch tensor 在 gpu 上
numpy_array = pytorch_tensor1.cpu().numpy()

需要注意 GPU 上的 Tensor 不能直接转换为 NumPy ndarray，需要使用`.cpu()`先将 GPU 上的 Tensor 转到 CPU 上

### 1.2 PyTorch Tensor 使用 GPU 加速



使用GPU能够加快矩阵的计算，通过如下的方法能够检测当前的电脑上是否支持CUDA

In [5]:
import torch
torch.cuda.is_available()

True

我们可以使用以下两种方式将 Tensor 放到 GPU 上

In [6]:
# 第一种方式是定义 cuda 数据类型
dtype = torch.cuda.FloatTensor # 定义默认 GPU 的 数据类型
gpu_tensor = torch.randn(10, 20).type(dtype)

# 第二种方式更简单，推荐使用
gpu_tensor = torch.randn(10, 20).cuda(0) # 将 tensor 放到第一个 GPU 上
#gpu_tensor = torch.randn(10, 20).cuda(1) # 将 tensor 放到第二个 GPU 上

print(dtype)

<class 'torch.cuda.FloatTensor'>


使用第一种方式将 tensor 放到 GPU 上的时候会将数据类型转换成定义的类型，而是用第二种方式能够直接将 tensor 放到 GPU 上，类型跟之前保持一致

推荐在定义 tensor 的时候就明确数据类型，然后直接使用第二种方法将 tensor 放到 GPU 上

而将 tensor 放回 CPU 的操作如下

In [7]:
cpu_tensor = gpu_tensor.cpu()

Tensor 属性的访问方式

In [8]:
# 可以通过下面两种方式得到 tensor 的大小
print(pytorch_tensor1.shape)
print(pytorch_tensor1.size())

torch.Size([3, 4])
torch.Size([3, 4])


In [9]:
# 得到 tensor 的数据类型
print(pytorch_tensor1.type())
print(gpu_tensor.type())

torch.DoubleTensor
torch.cuda.FloatTensor


In [11]:
# 得到 tensor 的维度
print(pytorch_tensor1.dim())

2


In [12]:
# 得到 tensor 的所有元素个数
print(pytorch_tensor1.numel())

12


## 2. Tensor的操作
Tensor 操作中的 API 和 NumPy 非常相似，如果熟悉 NumPy 中的操作，那么 tensor 基本操作是一致的，下面列举其中的一些操作

### 2.1 基本操作

In [10]:
x = torch.ones(3, 2)
print(x) # 这是一个float tensor

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [11]:
print(x.type())

torch.FloatTensor


In [12]:
# 将其转化为整形
x = x.long()
# x = x.type(torch.LongTensor)
print(x)

tensor([[1, 1],
        [1, 1],
        [1, 1]])


In [13]:
# 再将其转回 float
x = x.float()
# x = x.type(torch.FloatTensor)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [14]:
x = torch.randn(4, 3)
print(x)

tensor([[ 1.0198,  0.2343,  1.0258],
        [-1.1469, -0.2524,  1.0903],
        [-0.0993,  0.4383, -0.5869],
        [-0.1567, -0.3490,  0.7412]])


In [15]:
# 沿着行取最大值
max_value, max_idx = torch.max(x, dim=1)

In [16]:
# 每一行的最大值
max_value

tensor([1.0258, 1.0903, 0.4383, 0.7412])

In [17]:
# 每一行最大值的下标
max_idx

tensor([2, 2, 1, 2])

In [18]:
# 沿着行对 x 求和
sum_x = torch.sum(x, dim=1)
print(sum_x)

tensor([ 2.2799, -0.3089, -0.2478,  0.2355])


In [19]:
# 增加维度或者减少维度
print(x.shape)
x = x.unsqueeze(0) # 在第一维增加
print(x.shape)
print(x)

torch.Size([4, 3])
torch.Size([1, 4, 3])
tensor([[[ 1.0198,  0.2343,  1.0258],
         [-1.1469, -0.2524,  1.0903],
         [-0.0993,  0.4383, -0.5869],
         [-0.1567, -0.3490,  0.7412]]])


In [20]:
x = x.unsqueeze(1) # 在第二维增加
print(x.shape)

torch.Size([1, 1, 4, 3])


In [21]:
x = x.squeeze(0) # 减少第一维
print(x.shape)
print(x)

torch.Size([1, 4, 3])
tensor([[[ 1.0198,  0.2343,  1.0258],
         [-1.1469, -0.2524,  1.0903],
         [-0.0993,  0.4383, -0.5869],
         [-0.1567, -0.3490,  0.7412]]])


In [22]:
x = x.squeeze() # 将 tensor 中所有的一维全部都去掉
print(x.shape)

torch.Size([4, 3])


In [23]:
x = torch.randn(3, 4, 5)
print(x.shape)

# 使用permute和transpose进行维度交换
x = x.permute(1, 0, 2) # permute 可以重新排列 tensor 的维度
print(x.shape)

x = x.transpose(0, 2)  # transpose 交换 tensor 中的两个维度
print(x.shape)

torch.Size([3, 4, 5])
torch.Size([4, 3, 5])
torch.Size([5, 3, 4])


In [24]:
# 使用 view 对 tensor 进行 reshape
x = torch.randn(3, 4, 5)
print(x.shape)

x = x.view(-1, 5) # -1 表示任意的大小，5 表示第二维变成 5
print(x.shape)

x = x.view(3, 20) # 重新 reshape 成 (3, 20) 的大小
print(x.shape)

torch.Size([3, 4, 5])
torch.Size([12, 5])
torch.Size([3, 20])


In [30]:
x = torch.randn(3, 4)
y = torch.randn(3, 4)

# 两个 tensor 求和
z = x + y
# z = torch.add(x, y)
print(z)

tensor([[ 1.1539, -1.1664, -2.5307, -0.6083],
        [-2.6989, -3.7927, -0.9480,  0.8790],
        [-0.7401,  0.7780, -0.4375, -1.1361]])


### 2.2 `inplace`操作

PyTorch中大多数的操作都支持 `inplace` 操作，也就是可以直接对 tensor 进行操作而不需要另外开辟内存空间，方式非常简单，一般都是在操作的符号后面加`_`，比如

In [25]:
x = torch.ones(3, 3)
print(x.shape)

# unsqueeze 进行 inplace
x.unsqueeze_(0)
print(x.shape)

# transpose 进行 inplace
x.transpose_(1, 0)
print(x.shape)

torch.Size([3, 3])
torch.Size([1, 3, 3])
torch.Size([3, 1, 3])


In [26]:
x = torch.ones(3, 3)
y = torch.ones(3, 3)
print(x)

# add 进行 inplace
x.add_(y)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


## 练习题


* 查阅[PyTorch的Tensor文档](http://pytorch.org/docs/tensors.html)了解 tensor 的数据类型，创建一个 float64、大小是 3 x 2、随机初始化的 tensor，将其转化为 numpy 的 ndarray，输出其数据类型
* 查阅[PyTorch的Tensor文档](http://pytorch.org/docs/tensors.html)了解 tensor 更多的 API，创建一个 float32、4 x 4 的全为1的矩阵，将矩阵正中间 2 x 2 的矩阵，全部修改成2

## 参考
* [PyTorch官方说明文档](https://pytorch.org/docs/stable/)
* http://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html
* http://cs231n.github.io/python-numpy-tutorial/